name: demo.config
imports: []
definedTypes:
- name: ScalingType
  kind: Enum
  ordered: false
  possibleValues:
  - Elastic
  - Manual
- minLength: null
  regex: '[ABC][123]'
  kind: ConstrainedText
  maxLength: null
  name: SubComponentCode
- name: CloudProvider
  kind: Enum
  ordered: false
  possibleValues:
  - AWS
  - Azure
  - GCP
  - CP4
  - CP5
- min:
    v: '0.0'
    exclusive: false
  step: null
  name: ZeroTo1200
  kind: ConstrainedNum
  max:
    v: '1200.0'
    exclusive: false
  underlying: Number
- name: ZeroTo2400
  underlying: Number
  max:
    v: '2400.0'
    exclusive: false
  step: null
  min:
    v: '0.0'
    exclusive: false
  kind: ConstrainedNum
- kind: ConstrainedText
  maxLength: 36
  minLength: 8
  regex: ^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$
  name: Email
- name: CustomerRequest
  kind: Struct
  members:
  - isAbstract: false
    required: false
    singular: null
    name: cloudProvider
    type: demo.config.CloudProvider
    multiplicity: '1'
    gender: null
    kind: Attribute
  - name: mustHaveDedicatedEnv
    singular: null
    isAbstract: false
    multiplicity: '1'
    required: false
    kind: Attribute
    gender: null
    type: Boolean
  - gender: null
    kind: Attribute
    singular: null
    required: false
    isAbstract: false
    type: Boolean
    multiplicity: '1'
    name: mustHavePrivateEndpoints
  - singular: null
    type: Boolean
    name: mustHaveSubSecondLatency
    required: false
    gender: null
    multiplicity: '1'
    kind: Attribute
    isAbstract: false
  - type: Boolean
    singular: null
    required: false
    gender: null
    isAbstract: false
    name: isProductionUseCase
    kind: Attribute
    multiplicity: '1'
  - gender: null
    type: Number
    multiplicity: '1'
    isAbstract: false
    singular: null
    name: ingress
    required: false
    kind: Attribute
  - multiplicity: '1'
    name: egress
    isAbstract: false
    gender: null
    required: false
    kind: Attribute
    singular: null
    type: Number
  - isAbstract: false
    gender: null
    kind: Attribute
    type: Number
    multiplicity: '1'
    name: throughput
    required: false
    singular: null
  - gender: null
    multiplicity: '1'
    isAbstract: false
    name: numberOfConnections
    kind: Attribute
    singular: null
    required: false
    type: Integer
- name: Configuration
  parent: null
  kind: Entity
  members:
  - type: demo.config.Cluster
    multiplicity: '1'
    required: false
    name: cluster
    kind: Has
    gender: null
    singular: null
- name: Cluster
  parent: null
  kind: Entity
  members:
  - kind: Attribute
    type: demo.config.ScalingType
    required: false
    multiplicity: '1'
    gender: null
    name: scaling
    isAbstract: false
    singular: null
  - multiplicity: '1'
    singular: null
    type: Integer
    kind: Attribute
    name: minNumberOfNodes
    required: false
    isAbstract: false
    gender: null
- name: StandardCluster
  parent: demo.config.Cluster
  kind: Entity
  members:
  - name: subComponents
    gender: null
    kind: Has
    required: false
    multiplicity: 1+
    type: demo.config.SubComponent
    singular: subComponent
  - name: scaling
    kind: Attribute
    required: false
    gender: null
    multiplicity: '1'
    type: demo.config.ScalingType
    singular: null
    isAbstract: false
  - kind: Attribute
    isAbstract: false
    required: false
    gender: null
    name: minNumberOfNodes
    singular: null
    multiplicity: '1'
    type: Integer
- name: DedicatedCluster
  parent: demo.config.Cluster
  kind: Entity
  members:
  - type: demo.config.OptionalComponent
    gender: null
    singular: null
    multiplicity: 0..1
    required: false
    kind: Has
    name: optionalComponent
  - multiplicity: '1'
    gender: null
    name: scaling
    type: demo.config.ScalingType
    isAbstract: false
    required: false
    kind: Attribute
    singular: null
  - singular: null
    isAbstract: false
    name: minNumberOfNodes
    type: Integer
    required: false
    multiplicity: '1'
    kind: Attribute
    gender: null
- name: EnterpriseCluster
  parent: demo.config.Cluster
  kind: Entity
  members:
  - name: optionalComponent
    singular: null
    gender: null
    kind: Has
    type: demo.config.OptionalComponent
    required: false
    multiplicity: 0..1
  - multiplicity: '1'
    kind: Attribute
    isAbstract: false
    gender: null
    required: false
    name: scaling
    type: demo.config.ScalingType
    singular: null
  - singular: null
    name: minNumberOfNodes
    required: false
    kind: Attribute
    isAbstract: false
    type: Integer
    gender: null
    multiplicity: '1'
- name: BasicCluster
  parent: demo.config.Cluster
  kind: Entity
  members:
  - gender: null
    isAbstract: false
    type: demo.config.ScalingType
    required: false
    name: scaling
    singular: null
    multiplicity: '1'
    kind: Attribute
  - kind: Attribute
    isAbstract: false
    singular: null
    required: false
    gender: null
    name: minNumberOfNodes
    type: Integer
    multiplicity: '1'
- name: FreightCluster
  parent: demo.config.Cluster
  kind: Entity
  members:
  - type: demo.config.ScalingType
    name: scaling
    kind: Attribute
    singular: null
    required: false
    gender: null
    multiplicity: '1'
    isAbstract: false
  - isAbstract: false
    name: minNumberOfNodes
    gender: null
    singular: null
    required: false
    multiplicity: '1'
    type: Integer
    kind: Attribute
- name: OptionalComponent
  parent: null
  kind: Entity
  members: []
- name: OptionA
  parent: demo.config.OptionalComponent
  kind: Entity
  members:
  - singular: null
    name: quantity
    gender: null
    kind: Attribute
    multiplicity: '1'
    required: false
    isAbstract: false
    type: demo.config.ZeroTo1200
- name: OptionB
  parent: demo.config.OptionalComponent
  kind: Entity
  members: []
- name: EmailNotification
  parent: demo.config.OptionB
  kind: Entity
  members:
  - multiplicity: '1'
    type: demo.config.Email
    required: false
    kind: Attribute
    name: email
    singular: null
    gender: null
    isAbstract: false
- name: OptionB2
  parent: demo.config.OptionB
  kind: Entity
  members:
  - name: quantity
    type: demo.config.ZeroTo2400
    kind: Attribute
    required: false
    multiplicity: '1'
    singular: null
    isAbstract: false
    gender: null
- name: SubSubComponent
  kind: Struct
  members:
  - type: Text
    required: false
    isAbstract: false
    singular: null
    kind: Attribute
    multiplicity: '1'
    name: description
    gender: null
- name: SubComponent
  parent: null
  kind: Entity
  members:
  - isAbstract: false
    name: code
    gender: null
    kind: Attribute
    required: false
    singular: null
    multiplicity: '1'
    type: demo.config.SubComponentCode
  - singular: null
    kind: Attribute
    multiplicity: '1'
    isAbstract: false
    type: demo.config.ZeroTo2400
    required: false
    name: capacity
    gender: null
  - required: false
    singular: subSubComponent
    kind: Has
    name: subSubComponents
    type: demo.config.SubSubComponent
    gender: null
    multiplicity: 0+
