name: demo.config
imports: []
definedTypes:
- name: ScalingType
  kind: Enum
  ordered: false
  possibleValues:
  - Elastic
  - Manual
- minLength: null
  name: SubComponentCode
  maxLength: null
  kind: ConstrainedText
  regex: '[ABC][123]'
- name: CloudProvider
  kind: Enum
  ordered: false
  possibleValues:
  - AWS
  - Azure
  - GCP
  - CP4
  - CP5
- kind: ConstrainedNum
  max:
    v: '1200.0'
    exclusive: false
  underlying: Number
  step: null
  name: ZeroTo1200
  min:
    v: '0.0'
    exclusive: false
- step: null
  name: ZeroTo2400
  kind: ConstrainedNum
  underlying: Number
  max:
    v: '2400.0'
    exclusive: false
  min:
    v: '0.0'
    exclusive: false
- maxLength: 36
  kind: ConstrainedText
  regex: ^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$
  minLength: 8
  name: Email
- name: CustomerRequest
  kind: Struct
  members:
  - multiplicity: '1'
    gender: null
    isAbstract: false
    singular: null
    type: demo.config.CloudProvider
    name: cloudProvider
    kind: Attribute
    required: false
  - isAbstract: false
    singular: null
    multiplicity: '1'
    type: Boolean
    required: false
    name: mustHaveDedicatedEnv
    kind: Attribute
    gender: null
  - singular: null
    name: mustHavePrivateEndpoints
    gender: null
    kind: Attribute
    multiplicity: '1'
    required: false
    type: Boolean
    isAbstract: false
  - gender: null
    required: false
    multiplicity: '1'
    kind: Attribute
    singular: null
    type: Boolean
    name: mustHaveSubSecondLatency
    isAbstract: false
  - type: Boolean
    required: false
    gender: null
    name: isProductionUseCase
    singular: null
    multiplicity: '1'
    isAbstract: false
    kind: Attribute
  - type: Number
    isAbstract: false
    gender: null
    singular: null
    required: false
    kind: Attribute
    name: ingress
    multiplicity: '1'
  - kind: Attribute
    gender: null
    multiplicity: '1'
    name: egress
    type: Number
    isAbstract: false
    singular: null
    required: false
  - kind: Attribute
    isAbstract: false
    gender: null
    type: Number
    multiplicity: '1'
    singular: null
    required: false
    name: throughput
  - kind: Attribute
    required: false
    type: Integer
    isAbstract: false
    multiplicity: '1'
    gender: null
    name: numberOfConnections
    singular: null
- name: Configuration
  parent: null
  kind: Entity
  members:
  - required: false
    multiplicity: '1'
    kind: Has
    type: demo.config.Cluster
    name: cluster
    singular: null
    gender: null
- name: Cluster
  parent: null
  kind: Entity
  members:
  - gender: null
    kind: Attribute
    required: false
    type: demo.config.ScalingType
    multiplicity: '1'
    singular: null
    isAbstract: false
    name: scaling
  - isAbstract: false
    required: false
    kind: Attribute
    name: minNumberOfNodes
    multiplicity: '1'
    gender: null
    type: Integer
    singular: null
- name: StandardCluster
  parent: demo.config.Cluster
  kind: Entity
  members:
  - kind: Has
    singular: subComponent
    required: false
    multiplicity: 1+
    name: subComponents
    gender: null
    type: demo.config.SubComponent
  - multiplicity: '1'
    isAbstract: false
    required: false
    singular: null
    name: scaling
    gender: null
    type: demo.config.ScalingType
    kind: Attribute
  - singular: null
    type: Integer
    isAbstract: false
    multiplicity: '1'
    name: minNumberOfNodes
    required: false
    kind: Attribute
    gender: null
- name: DedicatedCluster
  parent: demo.config.Cluster
  kind: Entity
  members:
  - name: optionalComponent
    multiplicity: 0..1
    type: demo.config.OptionalComponent
    gender: null
    required: false
    singular: null
    kind: Has
  - isAbstract: false
    required: false
    name: scaling
    multiplicity: '1'
    type: demo.config.ScalingType
    gender: null
    singular: null
    kind: Attribute
  - name: minNumberOfNodes
    gender: null
    kind: Attribute
    type: Integer
    isAbstract: false
    required: false
    multiplicity: '1'
    singular: null
- name: EnterpriseCluster
  parent: demo.config.Cluster
  kind: Entity
  members:
  - gender: null
    kind: Has
    name: optionalComponent
    multiplicity: 0..1
    required: false
    type: demo.config.OptionalComponent
    singular: null
  - multiplicity: '1'
    required: false
    name: scaling
    kind: Attribute
    type: demo.config.ScalingType
    isAbstract: false
    singular: null
    gender: null
  - gender: null
    required: false
    multiplicity: '1'
    kind: Attribute
    name: minNumberOfNodes
    isAbstract: false
    singular: null
    type: Integer
- name: BasicCluster
  parent: demo.config.Cluster
  kind: Entity
  members:
  - gender: null
    singular: null
    required: false
    name: scaling
    isAbstract: false
    type: demo.config.ScalingType
    multiplicity: '1'
    kind: Attribute
  - gender: null
    name: minNumberOfNodes
    type: Integer
    isAbstract: false
    required: false
    multiplicity: '1'
    kind: Attribute
    singular: null
- name: FreightCluster
  parent: demo.config.Cluster
  kind: Entity
  members:
  - multiplicity: '1'
    required: false
    name: scaling
    gender: null
    isAbstract: false
    singular: null
    kind: Attribute
    type: demo.config.ScalingType
  - name: minNumberOfNodes
    singular: null
    kind: Attribute
    required: false
    isAbstract: false
    gender: null
    multiplicity: '1'
    type: Integer
- name: OptionalComponent
  parent: null
  kind: Entity
  members: []
- name: OptionA
  parent: demo.config.OptionalComponent
  kind: Entity
  members:
  - name: quantity
    singular: null
    multiplicity: '1'
    kind: Attribute
    required: false
    type: demo.config.ZeroTo1200
    isAbstract: false
    gender: null
- name: OptionB
  parent: demo.config.OptionalComponent
  kind: Entity
  members: []
- name: EmailNotification
  parent: demo.config.OptionB
  kind: Entity
  members:
  - required: false
    isAbstract: false
    kind: Attribute
    name: email
    singular: null
    type: demo.config.Email
    multiplicity: '1'
    gender: null
- name: OptionB2
  parent: demo.config.OptionB
  kind: Entity
  members:
  - isAbstract: false
    required: false
    multiplicity: '1'
    singular: null
    gender: null
    type: demo.config.ZeroTo2400
    kind: Attribute
    name: quantity
- name: SubSubComponent
  kind: Struct
  members:
  - isAbstract: false
    required: false
    singular: null
    gender: null
    type: Text
    multiplicity: '1'
    kind: Attribute
    name: description
- name: SubComponent
  parent: null
  kind: Entity
  members:
  - required: false
    singular: null
    kind: Attribute
    type: demo.config.SubComponentCode
    isAbstract: false
    name: code
    multiplicity: '1'
    gender: null
  - name: capacity
    gender: null
    type: demo.config.ZeroTo2400
    multiplicity: '1'
    required: false
    singular: null
    kind: Attribute
    isAbstract: false
  - gender: null
    type: demo.config.SubSubComponent
    kind: Has
    singular: subSubComponent
    required: false
    name: subSubComponents
    multiplicity: 0+
