$type: Block
stmts:
- $type: ForStmt
  tupleGen:
    bind:
      param: ssc
      collBType: List[NEList[Any]]
      coll:
        $type: Nav
        obj:
          $type: Ref
          id: compo
        elems:
        - - subSubComponents
          - List[demo.config.SubSubComponent]
      functor:
        $type: Coll
        type: Any
        elems:
        - $type: Tup
          elems:
          - $type: SLit
            s: compo
          - $type: Ref
            id: compo
        - $type: Tup
          elems:
          - $type: SLit
            s: ssc
          - $type: Ref
            id: ssc
      $type: Map
    filter:
    - $type: NativeFunApp
      funDef: luego.text.startsWith
      args:
      - $type: Nav
        obj:
          $type: Ref
          id: compo
        elems:
        - - code
          - demo.config.SubComponentCode
      - $type: SLit
        s: C
    param: compo
    coll:
      $type: Nav
      obj:
        $type: Ref
        id: the standard cluster
      elems:
      - - subComponents
        - NEList[demo.config.SubComponent]
    collBType: List[NEList[Any]]
    $type: FlMap
  stmts:
  - $type: Need
    exps:
    - $type: Nav
      obj:
        $type: Ref
        id: ssc
      elems:
      - - description
        - Text
e:
  $type: NativeFunApp
  funDef: luego.text.println
  args:
  - $type: SLit
    s: configure standard cluster based on subcomponents
