---
imports:
  - luego.text.*
  - demo.config.*

output: Unit
inputs:
  - name: the customer request
    type: demo.config.CustomerRequest
  - name: the configuration
    type: demo.config.Configuration
    mutable: true

definition: >
  {
    //set the cloudProvider of `the configuration` = the cloudProvider of `the customer request`;
    set the minNumberOfNodes of the cluster of `the configuration` = 7;
    println('Hello, playing with some update');
  } 

###
exposable: false
description: An operation that can infer modifications to be applied to the configuration input parameter.
usedDecisions: []
